[package]
name = "abc172"
version = "0.1.0"
authors = ["koka <koka.code@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
